export type OfferPackage={
  slug:string;
  title:string;
  audience:string;
  summary:string;
  items:string[];
  primaryService?:string;
  salesAngle:string;
  seasonal?:boolean;
};

export const offerPackages:OfferPackage[]=[
{slug:"company-launch",title:"تأسيس شركة من الصفر",audience:"الشركات الجديدة",summary:"هوية ومطبوعات وواجهة وحضور رقمي في حزمة إطلاق واحدة.",items:["هوية بصرية","كروت وأوراق رسمية","بروفايل","لوحة وواجهة","قوالب سوشال ميديا"],primaryService:"company-profile",salesAngle:"ابدأ بصورة احترافية منذ اليوم الأول بدل جمع الموردين والخدمات واحدة واحدة."},
{slug:"store-opening",title:"افتتاح متجر",audience:"التجزئة",summary:"كل ما يحتاجه المتجر من الهوية حتى مواد الافتتاح ونقطة البيع.",items:["تصميم الواجهة","اللوحة","أكياس","استيكرات","بطاقات أسعار","حملة افتتاح"],primaryService:"shop-sign",salesAngle:"حوّل الافتتاح إلى لحظة بيع حقيقية بهوية موحدة من الشارع حتى الكيس."},
{slug:"restaurant-launch",title:"افتتاح مطعم أو مقهى",audience:"الأغذية والمشروبات",summary:"حل متكامل للهوية والتغليف والمنيو والواجهة والترويج.",items:["منيو","علب وأكياس","استيكرات","يونيفورم","لوحة","مواد افتتاح"],primaryService:"product-boxes",salesAngle:"اجعل تجربة العلامة تبدأ من الواجهة وتستمر حتى آخر علبة تخرج مع العميل."},
{slug:"product-launch",title:"إطلاق منتج جديد",audience:"المصانع والعلامات",summary:"من تصميم العبوة إلى مواد نقطة البيع وحملة الإطلاق.",items:["Packaging","Labels","Mockups","كتالوج/بروشور","POS","حملة إطلاق"],primaryService:"product-boxes",salesAngle:"منتج واحد، نظام بصري واحد، وتنفيذ واحد بدل ملفات متناثرة بين عدة جهات."},
{slug:"corporate-anniversary",title:"ذكرى تأسيس المؤسسة",audience:"المؤسسات الكبرى",summary:"نحوّل الذكرى السنوية إلى مشروع محتوى وسمعة وهدايا وفعالية.",items:["مجلة الذكرى","كتاب تاريخ المؤسسة","Timeline","هدايا","فعالية","حملة رقمية"],primaryService:"corporate-anniversary-magazine",salesAngle:"لا تمر الذكرى السنوية كمنشور عابر. حوّل تاريخ المؤسسة إلى إصدار ومناسبة وأصل تسويقي."},
{slug:"calendar-2027",title:"موسم تقاويم 2027",audience:"الشركات والمؤسسات",summary:"حزمة تقاويم مكتبية وحائطية وأجندات وهدايا سنوية قابلة للتخصيص.",items:["تقويم مكتبي","تقويم حائطي","أجندة","بطاقات تهنئة","تغليف هدايا"],primaryService:"desk-calendar-2027",salesAngle:"اجعل علامتك على مكتب العميل طوال 365 يومًا.",seasonal:true},
{slug:"fleet-branding",title:"هوية أسطول المركبات",audience:"الشركات اللوجستية والخدمية",summary:"تصميم وتوحيد وتطبيق الهوية على مركبات المؤسسة.",items:["نظام تصميم","ملفات لكل مركبة","طباعة","تركيب","دليل صيانة"],primaryService:"vehicle-branding",salesAngle:"كل مركبة تصبح مساحة إعلان متحركة ضمن نظام واحد قابل للتكرار."},
{slug:"conference",title:"تجهيز مؤتمر أو فعالية",audience:"المنظمات والشركات",summary:"حل إنتاجي كامل من التسجيل والهوية حتى القاعة والهدايا.",items:["Backdrop","Roll-ups","Badges","Folders","Certificates","Gifts"],primaryService:"event-backdrop",salesAngle:"مورد واحد يدير الصورة الكاملة للفعالية بدل التنسيق مع سلسلة موردين."},
{slug:"pharmacy",title:"باقة الصيدلية",audience:"الصيدليات",summary:"مواد الهوية والبيع والتغليف والعروض داخل وخارج نقطة البيع.",items:["لوحة","أكياس","استيكر","بطاقات","عروض موسمية","يونيفورم"],primaryService:"shop-sign",salesAngle:"وحّد حضور الصيدلية من الواجهة إلى أكياس العميل والعروض الموسمية."},
{slug:"school",title:"باقة المدرسة",audience:"المدارس والمراكز",summary:"مطبوعات تعليمية وإدارية وإعلانية وهوية البيئة المدرسية.",items:["دفاتر ونماذج","بطاقات","شهادات","لوحات إرشادية","بروشور","فعاليات"],primaryService:"books",salesAngle:"نظام واحد لإدارة المطبوعات اليومية والموسمية والبيئة البصرية للمدرسة."},
{slug:"annual-print-plan",title:"عقد مطبوعات سنوي",audience:"الشركات ذات الطلب المتكرر",summary:"إدارة احتياج المؤسسة من الطباعة طوال العام بأسعار وشروط متفق عليها.",items:["قائمة أسعار خاصة","طلبات دورية","مخزون تصاميم","تقارير استهلاك","أولوية إنتاج"],salesAngle:"حوّل الطباعة من مشتريات متفرقة إلى خدمة مُدارة بتكلفة ووقت واضحين."},
{slug:"vip-gifts",title:"هدايا كبار العملاء",audience:"الشركات والبنوك",summary:"هدايا مخصصة راقية من الفكرة والتصميم حتى التغليف والتسليم.",items:["اختيار المنتجات","تخصيص","صندوق فاخر","بطاقة","تغليف وتسليم"],primaryService:"corporate-gift-kit",salesAngle:"هدية واحدة تحمل قيمة العلاقة وهوية المؤسسة، من المنتج حتى لحظة التسليم."},
{slug:"clinic-launch",title:"تجهيز عيادة أو مركز طبي",audience:"العيادات والمراكز الطبية",summary:"هوية المكان واللوحات والنماذج والمواد التوعوية في نظام واحد.",items:["لوحة خارجية","لوحات غرف","نماذج واستبيانات","بطاقات مواعيد","بروشورات","يونيفورم"],primaryService:"company-sign",salesAngle:"اجعل رحلة المراجع واضحة ومطمئنة من أول اللوحة حتى آخر نموذج."},
{slug:"hotel-hospitality",title:"هوية وتجهيز فندق أو منشأة ضيافة",audience:"الفنادق والشقق المفروشة",summary:"لوحات الغرف والإرشاد والمطبوعات والمواد الترحيبية والمنتجات المخصصة.",items:["لوحات غرف","دليل مرافق","بطاقات أبواب","منيوهات","Welcome Kit","لوحات إرشاد"],primaryService:"room-signs",salesAngle:"تجربة الضيف تبدأ من الإشارة الأولى وتستمر في كل تفصيل مطبوع داخل المنشأة."},
{slug:"real-estate-office",title:"باقة المكتب العقاري",audience:"العقار والتطوير",summary:"حضور بصري ومواد بيع للمشاريع والعقارات من الملف التعريفي إلى لوحات الموقع.",items:["بروفايل","بروشورات مشاريع","لوحات مواقع","فولدرات","نماذج حجز","Social Templates"],primaryService:"company-profile",salesAngle:"قدّم المشروع العقاري كعلامة موثوقة لا كإعلان عقار منفرد."},
{slug:"contractor-site",title:"تجهيز شركة مقاولات وموقع مشروع",audience:"المقاولات والهندسة",summary:"لوحات المشروع والسلامة والمطبوعات والتقارير وهوية الموقع الميدانية.",items:["لوحة مشروع","لوحات سلامة","نماذج موقع","بطاقات موظفين","تقارير","ملصقات معدات"],primaryService:"project-site-sign",salesAngle:"اجعل الموقع نفسه واجهة احترافية توثق المشروع وتدعم الثقة والسلامة."},
{slug:"factory-branding",title:"هوية مصنع ومنتجاته",audience:"المصانع",summary:"هوية المصنع والمنتج والتغليف والليبل والكتالوج ومواد البيع.",items:["هوية منتج","Packaging","Labels","كتالوج","لوحات المصنع","عينات مبيعات"],primaryService:"product-labels",salesAngle:"اربط المصنع بالمنتج في نظام بصري واحد جاهز للبيع والتوسع."},
{slug:"beauty-salon",title:"باقة صالون ومركز تجميل",audience:"الجمال والعناية",summary:"واجهة وهوية وخدمات مطبوعة وتغليف ومنيو أسعار ومحتوى بصري.",items:["لوحة وواجهة","قائمة خدمات","بطاقات","أكياس","Labels","Social Kit"],primaryService:"shop-sign",salesAngle:"حوّل المكان إلى علامة بصرية متماسكة تصلح للتصوير والتوصية والتوسع."},
{slug:"retail-chain",title:"تجهيز سلسلة فروع",audience:"العلامات متعددة الفروع",summary:"نظام قابل للتكرار للواجهات ونقاط البيع والمطبوعات والافتتاحات.",items:["دليل تنفيذ الفروع","واجهات","لوحات إرشاد","POS","Opening Kit","قائمة مواد موحدة"],primaryService:"shop-sign",salesAngle:"افتح الفرع الثاني والعاشر بنفس الجودة والهوية دون إعادة اختراع كل شيء."},
{slug:"supermarket",title:"باقة السوبرماركت والتجزئة اليومية",audience:"السوبرماركت والمتاجر الكبيرة",summary:"أكياس وأسعار ولافتات عروض وأقسام ومواد نقاط البيع والتغليف.",items:["أكياس","Price Tags","Shelf Talkers","لوحات أقسام","ملصقات عروض","Checkout Branding"],primaryService:"paper-shopping-bag",salesAngle:"اجعل كل نقطة داخل المتجر تعمل لصالح البيع والوضوح والهوية."},
{slug:"graduation-season",title:"موسم التخرج",audience:"الجامعات والمدارس والطلاب",summary:"حلول احتفال وطباعة وهدايا وتصوير وهوية حفلات التخرج.",items:["دعوات","شهادات","Backdrop","دروع","هدايا","أوشحة وملابس"],primaryService:"graduation-season-kit",salesAngle:"حزمة واحدة تجعل الحفل والهدية والصورة والذكرى تحمل الهوية نفسها.",seasonal:true},
{slug:"ramadan-corporate",title:"رمضان للشركات",audience:"الشركات والمؤسسات",summary:"هدايا وحملات وبطاقات وتغليف موسمي للعملاء والموظفين.",items:["Gift Kit","بطاقات","تغليف","تقويم رمضاني","حملة بصرية","مواد داخلية"],primaryService:"ramadan-gift-kit",salesAngle:"حوّل الهدية الموسمية إلى نقطة تواصل راقية تحمل اسم المؤسسة دون مبالغة.",seasonal:true},
{slug:"hajj-umrah",title:"حملة حج وعمرة متكاملة",audience:"وكالات الحج والعمرة والحملات",summary:"مواد تعريف وإرشاد ونقل وملابس وحقائب ولافتات للحملة.",items:["أعلام ورايات","استيكر باصات","حقائب","بطاقات","لوحات إرشاد","ملابس فريق"],primaryService:"hajj-campaign-kit",salesAngle:"هوية موحدة للحملة من نقطة التجمع إلى المركبة والحقيبة والمرشد.",seasonal:true},
{slug:"publisher-author",title:"إطلاق كتاب أو إصدار",audience:"المؤلفون والناشرون",summary:"من تصميم الغلاف والإخراج إلى الطباعة والإطلاق والمواد الترويجية.",items:["تصميم غلاف","إخراج داخلي","طباعة","Bookmarks","Poster","Launch Kit"],primaryService:"books",salesAngle:"حوّل المخطوط إلى إصدار جاهز للعرض والبيع والإهداء."},
{slug:"bank-corporate",title:"باقة البنك والمؤسسة المالية",audience:"البنوك وشركات التمويل",summary:"مطبوعات مؤسسية ونماذج محكومة وهوية فروع وهدايا عملاء.",items:["Stationery","نماذج مرقمة","لوحات فروع","بطاقات","تقارير","VIP Gifts"],primaryService:"corporate-stationery-kit",salesAngle:"دقة واتساق في كل نقطة اتصال مطبوعة مع العميل والموظف والفرع."},
{slug:"employee-onboarding",title:"تجهيز الموظف الجديد",audience:"الموارد البشرية والشركات",summary:"Welcome Kit متكامل للموظفين الجدد يجمع الهوية والمطبوعات والهدايا.",items:["بطاقة موظف","دفتر وقلم","كوب أو قارورة","تيشيرت أو بولو","Welcome Card","Gift Box"],primaryService:"welcome-kit",salesAngle:"اجعل أول يوم عمل تجربة تحمل ثقافة المؤسسة لا مجرد تسليم بطاقة دوام."}
];

export function findPackage(slug:string){
  return offerPackages.find(pack=>pack.slug===slug);
}
